language: php
php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer update --prefer-source

script:
  - vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml

after_script:
  - vendor/bin/php-coveralls -v
